enum UseCaseStatus {
    OK = 'OK',
    NOT_FOUND = 'NOT_FOUND',
    MESSAGE_NOT_FOUND = 'MESSAGE_NOT_FOUND',
    UNAUTHORIZED = 'UNAUTHORIZED',
    ALREADY_VOTED = 'ALREADY_VOTED',
    VOTED = 'VOTED',
    NOT_OWNER_NOR_GRANTED = 'NOT_OWNER_NOR_GRANTED',
    ALREADY_SIGN_UP = 'ALREADY_SIGN_UP',
}

export default UseCaseStatus;
